---

- name: backup configuration
#  hosts: network 
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
#    - name: run show running-config on remote devices
#      cli_command:
#        command: show run
#      register: config
    
    - name: datadump
      cli_command: 
        command: terminal datadump

    - name: backup
      ios_config:
        backup: yes
#        defaults: true
#        backup_options:
#          filename: backup.cfg
#          dir_path: "/home/alex/network/backups/"
      register: config
            
#    - name: print output to screen
#      debug:
#        var: config.stdout_lines
#      
#    - name: get timestamp
#      command: date +%Y%m%d
#      register: timestamp
#        
#    - name: save config
#      copy:
#        content: "{{ config.stdout }}"
#        dest: "/home/alex/network/backups/sh_run_{{ inventory_hostname }}_{{ timestamp.stdout }}.txt"