#!/bin/bash

cd /home/alex/venv/
source ./bin/activate
cd /home/alex/network/
ansible-playbook /home/alex/network/backup_sw.yml > /home/alex/network/backup/log_file-$(date +"%d-%m-%Y").log 2>&1
# find /home/alex/network/backup -type f -mtime +30 -delete